spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/electricity}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.h2.console.enabled=false
